### ISSUE TITLE
Missing the default config for the telescope

### ISSUE THREAD

**Issue by bigduu** [aznhe21/actions-preview.nvim#10]
After the latest update, there are some changes when selecting operation with the telescope plugin, but the telescope item in the default config is nil value as below pic. That will throw an error after updating the Plugin

![image](https://github.com/aznhe21/actions-preview.nvim/assets/18681616/e821963a-a695-486e-8950-d3df384e0006)

**Comment by aznhe21** [comment]
Oh, sorry, I'll fix it right away.

**Comment by bigduu** [comment]
I have create a PR to fix it

**Comment by bigduu** [comment]
Could you please merge the PR?
