### ISSUE TITLE
Code Action Preview Not Working

### ISSUE THREAD

**Issue by m4xshen** [aznhe21/actions-preview.nvim#14]
The code action preview just show the string same as code actions. See the screenshot:
![issue](https://github.com/aznhe21/actions-preview.nvim/assets/74842863/11ad6f7b-8b49-4f61-8003-32afd9012df7)

I use lazy.nvim to install plugin.
My config:
```lua
   {
      "aznhe21/actions-preview.nvim",
      config = function()
         vim.keymap.set(
            { "v", "n" },
            "<Leader>ca",
            require("actions-preview").code_actions
         )
      end,
   },

```

**Comment by aznhe21** [comment]
See [FAQ](https://github.com/aznhe21/actions-preview.nvim#why-do-i-get-command--instead-of-a-diff). I'll update the message as it is confusing.
