### ISSUE TITLE
Support to Code Lens

### ISSUE THREAD

**Issue by KevenGoncalves** [aznhe21/actions-preview.nvim#21]
Many plugins are great showing the action but something that they are missing is the capability to do the same in CodeLens, would be great if this plugin do that

**Comment by aznhe21** [comment]
While an interesting feature, Code Lens is difficult to preview because it is a function that executes commands and because each Language Server has a different format.

I will close the issue as I cannot imagine any specifics, but feel free to reopen it if you have any ideas.
