### ISSUE TITLE
Not working preview

### ISSUE THREAD

**Issue by Mechanosec** [aznhe21/actions-preview.nvim#24]
<img width="645" alt="image" src="https://github.com/aznhe21/actions-preview.nvim/assets/25524311/07abba27-35e9-4663-86a8-a93b3015364b">
<img width="389" alt="image" src="https://github.com/aznhe21/actions-preview.nvim/assets/25524311/3ffcba94-54af-44a8-8328-328f07d32657">
<img width="428" alt="image" src="https://github.com/aznhe21/actions-preview.nvim/assets/25524311/2a80cb4b-d3d8-4355-b263-0cfc8228bc22">
<img width="572" alt="image" src="https://github.com/aznhe21/actions-preview.nvim/assets/25524311/8a31bfa9-3c67-4663-9e6c-bd028a332ec0">

**Comment by Mechanosec** [comment]
Can I disable preview?

**Comment by aznhe21** [comment]
No, you cannot. It would not be in the spirit of this plugin to disable previews.
