### ISSUE TITLE
Feature Request: Ignore end-of-line newlines by default, like neovim does

### ISSUE THREAD

**Issue by Parsifa1** [aznhe21/actions-preview.nvim#35]
Neovim can guess the newline character at the end of the line by itself and decide not to display ^M. I don’t know if this plug-in can achieve this. Thank you very much!
![image](https://github.com/aznhe21/actions-preview.nvim/assets/31800073/a65a40d7-2b93-46af-9ea7-371269c72a28)

**Comment by aznhe21** [comment]
Thanks for the report, this is a bug and I fixed it in #42. Check it out.
