### ISSUE TITLE
Adding custom code actions

### ISSUE THREAD

**Issue by lukoshkin** [aznhe21/actions-preview.nvim#38]
Can I somehow create my own "code action"? (not based on lsp, just an entry that will show up under certain circumstances in the list of available actions)

I guess I should use one of `make_value` / `make_make_display` fields, but am not sure how

**Comment by aznhe21** [comment]
No, this plugin is for code actions from LSP only.

FYI, you can start your own LSP server within Neovim, please refer to [the implementation in crates.nvim](https://github.com/Saecki/crates.nvim/blob/main/lua/crates/lsp.lua).
