### ISSUE TITLE
How to make the menu relative (nui)

### ISSUE THREAD

**Issue by ilan-schemoul** [aznhe21/actions-preview.nvim#41]
Hey,
I don't like how the menu takes the fullscreen I much prefer the https://github.com/weilbith/nvim-code-action-menu where the menu is relative to the cursor (otherwise I lose focus and the context of the rest of my code)
![image](https://github.com/aznhe21/actions-preview.nvim/assets/9869317/abe8cc42-9e4e-4328-b9d3-cebe55d87385)

I tried the following but it's not working
````lua
    backend = { "nui", "telescope" },
    nui = {
      layout = {
        relative = "cursor",
        position = {
          row = "100",
          col = "1",
        },
        size = {
          width = "20%",
          height = "20%",
        },
      },
    },
```

**Comment by ilan-schemoul** [comment]
Well for now I can use telescope with theme cursor
```lua
  config = function(_, opts)
    require("actions-preview").setup({
      backend = { "telescope", "nui" },
      telescope = vim.tbl_extend(
        "force",
        -- telescope theme: https://github.com/nvim-telescope/telescope.nvim#themes
        require("telescope.themes").get_cursor(),
        {
          make_value = nil,
          make_make_display = nil,
          previewer = false,
        }
      ),
    })
  end,
```
I don't think I can hide the prompt which is a bit annoying 
![Capture d'écran 2024-05-04 140931](https://github.com/aznhe21/actions-preview.nvim/assets/9869317/0457e8eb-b91b-47c9-a8ec-d6615fdc2001)

**Comment by aznhe21** [comment]
Thank you for your report. With #43, the `relative = "cursor"` setting now works in the nui backend.


Also, telescope is just a fuzzy finder, so I don't think you can hide the prompt.
