### ISSUE TITLE
Error executing vim.schedule lua callback: .../backend/telescope.lua:150: Invalid 'replacement': Expected Lua table

### ISSUE THREAD

**Issue by Parsifa1** [aznhe21/actions-preview.nvim#44]
![image](https://github.com/aznhe21/actions-preview.nvim/assets/31800073/f3a17104-af53-441c-a7dd-ba84a2d80a3e)

It seems something went wrong here...

when run `require("actions-preview").code_actions` , it occurs.

**Comment by crisidev** [comment]
I have the same issue and for me it comes with actions from none-ls, where `preview` is something like

```lua
{
  syntax = "",
  text = "Preview is not available for this action (command=NULL_LS_CODE_ACTION).\nThis is due to limitations of your language server (null-ls) implementation."
}
```

**Comment by crisidev** [comment]
I have roughly fixed it locally with something like this:

```lua
                if preview["text"] ~= nil then
                    lines = {}
                    for s in preview.text:gmatch("[^\r\n]+") do
                        table.insert(lines, s)
                    end
                    preview.lines = lines
                else
                    preview = preview or { syntax = "", lines = { "preview not available" } }
                end
```

**Comment by Parsifa1** [comment]
> I have roughly fixed it locally with something like this:
> 
> ```lua
>                 if preview["text"] ~= nil then
>                     lines = {}
>                     for s in preview.text:gmatch("[^\r\n]+") do
>                         table.insert(lines, s)
>                     end
>                     preview.lines = lines
>                 else
>                     preview = preview or { syntax = "", lines = { "preview not available" } }
>                 end
> ```

maybe you can make a pr!

**Comment by aznhe21** [comment]
Uh, sorry, I'll fix it right away; you don't have to give me a PR.

**Comment by aznhe21** [comment]
Fixed in #45. Please check it.

**Comment by Parsifa1** [comment]
Thanks for your quick response!

**Comment by crisidev** [comment]
Thanks a lot, unfortunately I did not have time to make a PR..
