### ISSUE TITLE
Option to disable preview

### ISSUE THREAD

**Issue by ilan-schemoul** [aznhe21/actions-preview.nvim#46]
Hello,
I wish I could disable previews as I just like having the popup menu not the preview :)
Or at least the possibility to put the preview below the list of actions so my eyes can first focus on what matters most to me.

**Comment by aznhe21** [comment]
You can achive that by using [stevearc/dressing.nvim](https://github.com/stevearc/dressing.nvim).

**Comment by ilan-schemoul** [comment]
Can you tell me more ?
I don't see what options control the preview ?

**Comment by aznhe21** [comment]
1. Install dressing.nvim (instead of actions-preview.nvim) and setup the plugin.
2. Run `:=vim.lsp.buf.code_action()`
