### ISSUE TITLE
Is there a way to apply code action by pressing a number key?

### ISSUE THREAD

**Issue by leiswatch** [aznhe21/actions-preview.nvim#7]
Firstly, thanks for this awesome plugin. Secondly, is there a way to execute code action by pressing key number, similar to [weilbith/nvim-code-action-menu](https://github.com/weilbith/nvim-code-action-menu)?

**Comment by aznhe21** [comment]
Thanks for your feedback. Unfortunately, it is not possible to support direct execution by key number due to the specifications of the backends. However, if you are using telescope.nvim, you can now filter by number through #8.
